### ISSUE TITLE
Add support for tutorial materials

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsdockerspawner#10]
Teachers should be able to write a shared directory, and students should be able to read the directory. 

@bnash @dtabell For the workshop, do you think there are issues with making the course materials available to all Jupyter users (not just participants)? If so, we will need the GitHub handles of all participants (not just speakers) prior to the workshop.

**Comment by bnash** [comment]
I will discuss this with @dtabell next week.
So far, one relevant issue here regards including copyrighted papers in the course material.  We may have permission to distribute these more narrowly for educational purposes, but have not clarified this.

**Comment by robnagler** [comment]
@bnash It's getting down to the wire to code this the way you want it. Please let me know if I can implement sharing with instructors as writers and anybody using Jupyter as a reader. If you want to restrict readers, you will have to provide GitHub handles for all participants before the workshop.

**Comment by bnash** [comment]
@robnagler, after discussion, I understand you have implemented the ability to create to a  directory in Jupyter that is writable by a few, but readable by all those logged in to the Jupyter server.  I would propose the name ZgoubiWorkshopExtras and is should be writable by myself and @dtabell.  Thanks!

**Comment by robnagler** [comment]
@bnash @dtabell This is running in beta-jupyter.radiasoft.org. Please check it out. You two and I have write privs, but other people will see a read-only directory. LMK, and I can push to prod.

**Comment by bnash** [comment]
Looks good, Rob.  Yes, you may push this to production jupyter.
