### ISSUE TITLE
Returning blacklist user

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsdockerspawner#25]
We had a blacklist user start a process. The IP wasn't blocked but DockerSpawner should have rejected the start.

**Comment by robnagler** [comment]
It's strange that this is happening. I don't understand why a blacklist user should be allowed to login. @e-carlin do you think this has something to do with our auth?

**Comment by e-carlin** [comment]
From the looks of it in 1.2 they [deprecated Authenticator.blackslist](https://github.com/jupyterhub/jupyterhub/pull/3090/files#diff-61a2bcd5f4ba0ddfd7674a8ef2f8b90d203362cc5aa24c5f3b160146374b0c5dL115) which is what we are using. But, they had a bug in the deprecation. They completely removed the config option instead of marking as deprecated (as they did for whitelist). I'll fix by using the new names.

**Comment by e-carlin** [comment]
My guess is you will see `Config option `blacklist` not recognized by `Authenticator`.` in the logs.

**Comment by robnagler** [comment]
No messages. We are using jupyterhub==1.1.0 and dockerspawner.git@0.11.1.

**Comment by e-carlin** [comment]
I realized we don't blacklist users anymore. Users who should no longer access the system should have the `sim_type_jupyterhublogin` role removed. Does that solve it?

**Comment by robnagler** [comment]
The role is not checked if they have already logged in, which I think is the problem.

**Comment by e-carlin** [comment]
Yes, jupyterhub.refresh_user needs to also check the role (call `require_sim_type`). And the role is actually not checked at all. jupyterhublogin is in `default_proprietary_sim_types` we only check `proprietary_sim_types`. I'll fix tomorrow.

**Comment by robnagler** [comment]
The check needs to happen when the container is deleted. That gives us a control point. 

We still need the blocked user list management for jupyterhub with github so leave it in.

If you want to change the names in rsconf to match jupyter's new use, but generate the old/new names in the conf.py that's fine.
