### ISSUE TITLE
429 error better message

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsdockerspawner#26]
If there are servers in the pool, then say the user needs to upgrade. If there are no servers in the pool, say the user needs to be approved. Look at formatting briefly to see if there's an easy way to trigger different errors.

**Comment by robnagler** [comment]
I configured a way to edit templates, which will be deployed from rsdockerspawner. Here is the prototype of error messages for the two cases:

![20210823_jupyter_noresource](https://user-images.githubusercontent.com/5495179/130527237-35dc0799-7deb-44d6-95ae-fc286b374599.jpg)

![20210823_jupyter_unverified](https://user-images.githubusercontent.com/5495179/130527251-ad627778-dbb7-412b-828d-dc3e5ae32ede.jpg)

We can have "any" HTML, but obviously, the more complex, the harder it will be to program. These involve minimal styling.

**Comment by bruhwiler** [comment]
Looks good.

**Comment by bruhwiler** [comment]
Looking again at the 2nd message, regarding first time Jupyter users, I see two typos.

"within one business days" should be "within one business day"

"feel free to use any of other Sirepo apps" should be "feel free to use any of the other Sirepo apps"

**Comment by robnagler** [comment]
Fixed
